# Generated by Django 3.2.9 on 2021-11-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastn', models.CharField(max_length=50)),
                ('sector', models.CharField(default='Sistemas', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantaName', models.CharField(max_length=50)),
                ('plantaLocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastn', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('costCenter', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='Incident description', max_length=100)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.analist')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.planta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
            ],
        ),
    ]
