# Generated by Django 3.2.9 on 2021-11-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analist',
            fields=[
                ('analist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastn', models.CharField(max_length=50)),
                ('sector', models.CharField(default='Sistemas', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('planta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plantaName', models.CharField(max_length=50)),
                ('plantaLocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastn', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('costCenter', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(default='Incident description', max_length=100)),
                ('analist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.analist')),
                ('planta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.planta')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
            ],
        ),
    ]
