# Generated by Django 3.2.9 on 2021-11-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_analist_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analist',
            name='password',
        ),
    ]
