# Generated by Django 3.2.9 on 2021-11-11 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_analist_id_analist_analista_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='analist_id',
            new_name='analista_id',
        ),
    ]
